### ISSUE TITLE
 Uncaught Error: Class 'Dompdf\Dompdf' not found in /var/www/html/magento217/app/code/LCB/DompdfDocuments/Model/Order/Pdf/Invoice.php:105

### ISSUE THREAD

**Issue by msliman** [lcbrq/magento2-LCB_DompdfDocuments#1]

**Comment by msliman** [comment]
Hi, I got this error in the title.

Can you help ?

**Comment by marekdan** [comment]
Hi, 
I was developing this extension when I was working for my previous employer. It's better to contact him if you need something more. My advice is to check in your magento project if there is module called "dompdf". It seems that module is not properly installed/activated or not installed at all.

**Comment by Tomasz-Silpion** [comment]
Hi, it seems that you've installed extension manually not using the packagist. If so, please add dompdf/dompdf dependency manually to your Magento 2 composer.
